# fly.toml app configuration file generated for code-test-delicate-star-9921 on 2025-06-15T04:16:56+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'code-test-delicate-star-9921'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
